import type { Metadata } from "next";
import { Macondo } from "next/font/google";
import "./globals.css";

const font = Macondo({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} text-white bg-[color:#10181c]`}>
        <div className="z-0 absolute w-full h-screen bg-[url('/images/dungeon.jpg')] bg-[position:center] bg-repeat-x filter blur-sm"></div>
        <main className="z-10 flex min-h-screen">{children}</main>
      </body>
    </html>
  );
}
