import type { Metadata } from "next";
import { Macondo } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const font = Macondo({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} text-white bg-[color:#10181c]`}>
        <main className="flex min-h-screen">
          <nav className="flex flex-col bg-[color:#ae3631] px-6 min-w-80 w-80">
            <div className="flex py-5 w-full">
              <Image
                src="/images/d20-icon.png"
                alt=""
                width={24}
                height={24}
              ></Image>
              <span className="ml-2">Dungeon Master Toolkit</span>
            </div>
            <a className="text-xl underline" href="/monsters">
              Monsters
            </a>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
