import type { Metadata } from "next";
import { Macondo } from "next/font/google";
import "./globals.css";

const font = Macondo({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} text-white bg-[color:#10181c]`}>
        <main className="flex min-h-screen">{children}</main>
      </body>
    </html>
  );
}
